name: Rishav Singh  # name defined

on: # event trigger
  push: # which event trigger
    branches: [ main ] # branches defined and code push to main branch

jobs: # initize job
  demo: # job name
    runs-on: ubuntu-latest # runner defined

    steps: # defined steps
      - name: Greeting # defined name
        run: echo "Hello from Rishav" # run command
